### PR TITLE
Various Plugin Improvements

### PR DESCRIPTION
**Pull request by justinbeaty**
While I was working on the other PHPStan issue, I was just going to go in here and remove the `MAHO_IS_CHILD_PROJECT` constant that we ended up not using, but I found some other things to do:

1) There was a controller class autoloader that we no longer need because of the work in Maho's composer plugin.

2) Removed references to `disableLocalModules`.

3) Deprecated `magentoRootPath` in favor of a `mahoRootDir` parameter. Either value can be null and we'll just use the current cwd.

4) Greatly simplified the `phpstan-bootstrap.php` file.

5) Merged `extension.neon` and `extension-mage-autoload.neon` into one. You can trigger the latter by setting `mahoUseStaticReflection: false` in `.phpstan.neon`

6) Removed some parameters from `extension.neon`. Some weren't needed and others were being overridden by Maho's `.phpstan.neon` anyway.

Note: the `callback: 'callable'` type alias should be moved to Maho's `.phpstan.neon`. It seems wrong to hide mistyped errors in the plugin since they can eventually be fixed. These are the changes I made `mahocommerce/maho/.phpstan.neon`:

```diff
diff --git a/.phpstan.neon b/.phpstan.neon
index facbee0ecb..cbe7030d6b 100644
--- a/.phpstan.neon
+++ b/.phpstan.neon
@@ -3,7 +3,7 @@ includes:
     - .phpstan.baseline.neon
     - phar://phpstan.phar/conf/bleedingEdge.neon
 parameters:
-    magentoRootPath: %currentWorkingDirectory%
+    # mahoUseStaticReflection: false
     phpVersion: 80200
     fileExtensions:
         - php
@@ -62,5 +62,6 @@ parameters:
     checkInternalClassCaseSensitivity: true
     treatPhpDocTypesAsCertain: false
     typeAliases:
+        callback: 'callable'
         Cm_RedisSession_Model_Session: 'Mage_Core_Model_Resource_Session'
     tmpDir: var
```

---

## Note about child projects

While I haven't tested using this plugin in a child project yet, I suspect we will need modify `src/Config/MagentoCore.php`, which overrides some of the methods in `Mage_Core_Model_Config_Base`. It will need to use the Maho composer plugin just like we do in the core file. OR, I'm pretty sure you could just disable the static analysis option and we'll load the actual config class and it should work.

---

## Testing

Probably easiest to just `cp -R` the files into your vendor folder to test.

### CODE REVIEW

**Comment by justinbeaty** [comment]
@fballiano tagging you in case you didn’t see this.

**Comment by fballiano** [comment]
@justinbeaty sorry, I saw it this morning and was wondering why I didn't receive a notification

**Comment by fballiano** [comment]
@justinbeaty this plugin was never tested for child projects so it's no problem ;-)

**Comment by justinbeaty** [comment]
> @justinbeaty this plugin was never tested for child projects so it's no problem ;-)

Yeah, the static reflection mode definitely won’t work, but I think the other mode will. We will fix it later, not a big deal now.

No problem on the delay, I just saw your phpstan version bump this morning and figured you saw this but just making sure.

**Pull request merged**
